AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB Table for Budget Bliss App

Resources:
  BudgetBlissTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BudgetBlissTransactions
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: BudgetBliss
